// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwwE0OrLDcV9UquUJ3jBjtM3yMG7e894U',
    appId: '1:948621901407:web:8d609944bf95d2a78ba5ea',
    messagingSenderId: '948621901407',
    projectId: 'agrotech-hackaton',
    authDomain: 'agrotech-hackaton.firebaseapp.com',
    storageBucket: 'agrotech-hackaton.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOwiM9ExBOx_fejXStXkh72h-TqbVhizg',
    appId: '1:948621901407:android:60576777ec1cd09f8ba5ea',
    messagingSenderId: '948621901407',
    projectId: 'agrotech-hackaton',
    storageBucket: 'agrotech-hackaton.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSpq0v9n4-sdEBasMA6nHsyeECcQhhPAQ',
    appId: '1:948621901407:ios:bad2cbd97db07f928ba5ea',
    messagingSenderId: '948621901407',
    projectId: 'agrotech-hackaton',
    storageBucket: 'agrotech-hackaton.firebasestorage.app',
    iosBundleId: 'com.example.agrotechHacakaton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSpq0v9n4-sdEBasMA6nHsyeECcQhhPAQ',
    appId: '1:948621901407:ios:bad2cbd97db07f928ba5ea',
    messagingSenderId: '948621901407',
    projectId: 'agrotech-hackaton',
    storageBucket: 'agrotech-hackaton.firebasestorage.app',
    iosBundleId: 'com.example.agrotechHacakaton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwwE0OrLDcV9UquUJ3jBjtM3yMG7e894U',
    appId: '1:948621901407:web:5bc3db05a9cac7bf8ba5ea',
    messagingSenderId: '948621901407',
    projectId: 'agrotech-hackaton',
    authDomain: 'agrotech-hackaton.firebaseapp.com',
    storageBucket: 'agrotech-hackaton.firebasestorage.app',
  );
}
